# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-14 10:28
from __future__ import unicode_literals

import courseManagement.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courseManagement', '0005_format_formatuuid'),
    ]

    operations = [
        migrations.CreateModel(
            name='course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courseId', models.CharField(default=courseManagement.models.getcourseId, max_length=200, unique=True)),
                ('courseCategoryId', models.TextField(blank=True, null=True)),
                ('fullName', models.TextField(blank=True, null=True)),
                ('shortName', models.TextField(blank=True, null=True)),
                ('visibility', models.TextField(blank=True, null=True)),
                ('startDate', models.DateTimeField(auto_now=True)),
                ('endDate', models.DateTimeField(auto_now=True)),
                ('summary', models.TextField(blank=True, null=True)),
                ('formatId', models.TextField(blank=True, null=True)),
                ('numberOfSection', models.TextField(blank=True, null=True)),
                ('hiddenSectionId', models.TextField(blank=True, null=True)),
                ('courseLayoutId', models.TextField(blank=True, null=True)),
                ('forceLanguageID', models.TextField(blank=True, null=True)),
                ('numOfAnnounment', models.TextField(blank=True, null=True)),
                ('showGradesToStudent', models.TextField(blank=True, null=True)),
                ('showActivityReport', models.TextField(blank=True, null=True)),
                ('enableCompletionTracking', models.TextField(blank=True, null=True)),
                ('maxUploadSize', models.TextField(blank=True, null=True)),
                ('createdDate', models.DateTimeField(auto_now_add=True)),
                ('modifiedDate', models.DateTimeField(auto_now=True)),
                ('isActive', models.BooleanField(default=True)),
                ('ModifiedBy', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='courseModifiedBy', to=settings.AUTH_USER_MODEL)),
                ('createdBy', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='courseCreatedBy', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='courseUUID',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuidNumber', models.BigIntegerField(default=0)),
            ],
        ),
    ]
