# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-14 10:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courseManagement', '0006_course_courseuuid'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='format',
            new_name='formattbl',
        ),
    ]
