# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-19 06:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courseManagement', '0009_auto_20180316_1419'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='endDate',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='startDate',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
