# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-19 12:55
from __future__ import unicode_literals

import courseManagement.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courseManagement', '0010_auto_20180319_1225'),
    ]

    operations = [
        migrations.CreateModel(
            name='badges',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('badgeId', models.CharField(default=courseManagement.models.getbadgesId, max_length=200, unique=True)),
                ('badgeName', models.TextField(blank=True, null=True)),
                ('issuerName', models.TextField(blank=True, null=True)),
                ('issuerContact', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('expiryDate', models.DateTimeField(blank=True, null=True)),
                ('createdBy', models.TextField(blank=True, null=True)),
                ('modifiedBy', models.TextField(blank=True, null=True)),
                ('createdDate', models.DateTimeField(auto_now_add=True)),
                ('modifiedDate', models.DateTimeField(auto_now=True)),
                ('isActive', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='badgesUUID',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuidNumber', models.BigIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='competencyFramework',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('compentencyId', models.CharField(default=courseManagement.models.getcompetencyFrameworkId, max_length=200, unique=True)),
                ('competencyName', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('scale', models.TextField(blank=True, null=True)),
                ('visibile', models.TextField(blank=True, null=True)),
                ('category', models.TextField(blank=True, null=True)),
                ('level1', models.TextField(blank=True, null=True)),
                ('level2', models.TextField(blank=True, null=True)),
                ('level3', models.TextField(blank=True, null=True)),
                ('level4', models.TextField(blank=True, null=True)),
                ('createdBy', models.TextField(blank=True, null=True)),
                ('modifiedBy', models.TextField(blank=True, null=True)),
                ('createdDate', models.DateTimeField(auto_now_add=True)),
                ('modifiedDate', models.DateTimeField(auto_now=True)),
                ('isActive', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='competencyFrameworkUUID',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuidNumber', models.BigIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='taxonomies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taxonomieId', models.CharField(default=courseManagement.models.gettaxonomiesId, max_length=200, unique=True)),
                ('taxonomieName', models.TextField(blank=True, null=True)),
                ('createdBy', models.TextField(blank=True, null=True)),
                ('modifiedBy', models.TextField(blank=True, null=True)),
                ('createdDate', models.DateTimeField(auto_now_add=True)),
                ('modifiedDate', models.DateTimeField(auto_now=True)),
                ('isActive', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='taxonomiesUUID',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuidNumber', models.BigIntegerField(default=0)),
            ],
        ),
    ]
