# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-23 07:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courseManagement', '0012_sample'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parentcategory',
            name='parentCategoryId',
        ),
    ]
