# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-23 07:57
from __future__ import unicode_literals

import courseManagement.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courseManagement', '0013_remove_parentcategory_parentcategoryid'),
    ]

    operations = [
        migrations.CreateModel(
            name='subCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subCategoryId', models.CharField(default=courseManagement.models.getsubCategoryId, max_length=200, unique=True)),
                ('parentCategoryId', models.TextField(blank=True, null=True)),
                ('subCategoryName', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('createdBy', models.TextField(blank=True, null=True)),
                ('modifiedBy', models.TextField(blank=True, null=True)),
                ('createdDate', models.DateTimeField(auto_now_add=True)),
                ('modifiedDate', models.DateTimeField(auto_now=True)),
                ('isActive', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='subCategoryUUID',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuidNumber', models.BigIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='userCourses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userCourseId', models.CharField(default=courseManagement.models.getuserCoursesId, max_length=200, unique=True)),
                ('userId', models.TextField(blank=True, null=True)),
                ('courseId', models.TextField(blank=True, null=True)),
                ('completionFlag', models.TextField(blank=True, null=True)),
                ('createdBy', models.TextField(blank=True, null=True)),
                ('modifiedBy', models.TextField(blank=True, null=True)),
                ('createdDate', models.DateTimeField(auto_now_add=True)),
                ('modifiedDate', models.DateTimeField(auto_now=True)),
                ('isActive', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='userCoursesUUID',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuidNumber', models.BigIntegerField(default=0)),
            ],
        ),
        migrations.DeleteModel(
            name='sample',
        ),
    ]
