# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-24 07:08
from __future__ import unicode_literals

import courseManagement.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courseManagement', '0014_auto_20180323_1327'),
    ]

    operations = [
        migrations.CreateModel(
            name='customFileUpload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom1', models.TextField(blank=True, null=True)),
                ('custom2', models.TextField(blank=True, null=True)),
                ('custom3', models.TextField(blank=True, null=True)),
                ('custom4', models.TextField(blank=True, null=True)),
                ('custom5', models.TextField(blank=True, null=True)),
                ('fileToUpload', models.FileField(blank=True, max_length=500, null=True, upload_to=courseManagement.models.get_upload_filepath)),
            ],
        ),
    ]
