# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-24 07:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('courseManagement', '0015_customfileupload'),
    ]

    operations = [
        migrations.AddField(
            model_name='customfileupload',
            name='createdDate',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customfileupload',
            name='isActive',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='customfileupload',
            name='modifiedDate',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
