# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-28 13:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courseManagement', '0017_cohort_cohortuuid'),
        ('courseManagement', '0013_auto_20180328_1630'),
    ]

    operations = [
    ]
