# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-03 08:09
from __future__ import unicode_literals

import coursecontent.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='pagecontent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pcid', models.CharField(default=coursecontent.models.pcontentid, max_length=200, unique=True)),
                ('name', models.TextField(blank=True, null=True)),
                ('desc', models.TextField(blank=True, null=True)),
                ('showdesc', models.BooleanField(default=True)),
                ('pcontent', models.TextField(blank=True, null=True)),
                ('displayname', models.BooleanField(default=True)),
                ('displaydesc', models.BooleanField(default=True)),
                ('tracking', models.CharField(max_length=128)),
                ('requireviewactivity', models.BooleanField(default=True)),
                ('recivegradetocomplete', models.BooleanField(default=True)),
                ('submittocomplete', models.BooleanField(default=True)),
                ('completedondate', models.DateField(blank=True, null=True)),
                ('tags', models.TextField(blank=True, null=True)),
                ('coursecompitancies', models.CharField(max_length=128)),
                ('uponactivitycompitancy', models.CharField(max_length=128)),
                ('isActive', models.BooleanField(default=True)),
                ('createdDate', models.DateTimeField(auto_now_add=True)),
                ('modifiedDate', models.DateTimeField(auto_now=True)),
                ('createdBy', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pagecontentCreatedBy', to=settings.AUTH_USER_MODEL)),
                ('modifiedBy', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pagecontentModifiedBy', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='pcontentsid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuidNumber', models.BigIntegerField(default=0)),
            ],
        ),
    ]
