# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-15 09:44
from __future__ import unicode_literals

import courselayout.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courselayout', '0004_social_activity_socialid'),
    ]

    operations = [
        migrations.CreateModel(
            name='topics_weekly_activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('twid', models.CharField(default=courselayout.models.gettpicweeklyid, max_length=200, unique=True)),
                ('noofsessions', models.IntegerField()),
                ('courseId', models.TextField(blank=True, null=True)),
                ('showallsections', models.BooleanField(default=True)),
                ('isActive', models.BooleanField(default=True)),
                ('createdDate', models.DateTimeField(auto_now_add=True)),
                ('modifiedDate', models.DateTimeField(auto_now=True)),
                ('createdBy', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='topicweklyactivityCreatedBy', to=settings.AUTH_USER_MODEL)),
                ('modifiedBy', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='topicweklyactivityModifiedBy', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='topicweeklyID',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuidNumber', models.BigIntegerField(default=0)),
            ],
        ),
    ]
